version: "3.3"
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: "db"
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: "root"
      # You can use whatever password you like
      POSTGRES_PASSWORD: "123"
      # Password for root access
    ports:
      - "3306:3306"
